version = "8.9"

try:
    import sys
    from PyQt5 import QtCore, QtGui, QtWidgets, Qt

    import calibrate
    import draw

except ImportError:
    print("please install all necessary dependencies first!\n--> pip install -r requirements.txt\nIf this error stays persistent, message me on discord: kolmus")
    exit()
    
class Ui_MainWindow(object):  # setting up the window

    def setupUi(self, MainWindow):

        MainWindow.setWindowIcon(QtGui.QIcon('logo.png'))  # logo
        MainWindow.setWindowFlags(
            MainWindow.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)  # make it always stay on top
        MainWindow.setObjectName(f"nuspli {version}")
        MainWindow.resize(379, 393)
        MainWindow.setMinimumSize(QtCore.QSize(379, 393))
        MainWindow.setMaximumSize(QtCore.QSize(379, 393))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        #  now all the widgets
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DrawmodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.DrawmodeLabel.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DrawmodeLabel.setFont(font)
        self.DrawmodeLabel.setObjectName("DrawmodeLabel")
        self.DrawmodeBox = QtWidgets.QComboBox(self.centralwidget)
        self.DrawmodeBox.setGeometry(QtCore.QRect(180, 20, 191, 21))
        self.DrawmodeBox.setObjectName("DrawmodeBox")
        self.DrawmodeBox.addItem("")
        self.DrawmodeBox.addItem("")
        self.DrawmodeBox.addItem("")
        self.DrawmodeBox.addItem("")
        self.DrawmodeBox.addItem("")
        self.DrawmodeBox.addItem("")
        self.BrushLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrushLabel.setGeometry(QtCore.QRect(10, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BrushLabel.setFont(font)
        self.BrushLabel.setObjectName("BrushLabel")
        self.LayerLabel = QtWidgets.QLabel(self.centralwidget)
        self.LayerLabel.setGeometry(QtCore.QRect(10, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LayerLabel.setFont(font)
        self.LayerLabel.setObjectName("LayerLabel")
        self.SpeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.SpeedLabel.setGeometry(QtCore.QRect(10, 110, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpeedLabel.setFont(font)
        self.SpeedLabel.setObjectName("SpeedLabel")
        self.PercentLabel = QtWidgets.QLabel(self.centralwidget)
        self.PercentLabel.setGeometry(QtCore.QRect(220, 110, 21, 21))
        self.PercentLabel.setObjectName("PercentLabel")
        self.CalibrateColorsButton = QtWidgets.QPushButton(self.centralwidget)
        self.CalibrateColorsButton.setGeometry(QtCore.QRect(70, 300, 81, 21))
        self.CalibrateColorsButton.setObjectName("CalibrateColorsButton")
        self.ColorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.ColorsLabel.setGeometry(QtCore.QRect(10, 300, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ColorsLabel.setFont(font)
        self.ColorsLabel.setObjectName("ColorsLabel")
        self.CanvasLabel = QtWidgets.QLabel(self.centralwidget)
        self.CanvasLabel.setGeometry(QtCore.QRect(10, 330, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CanvasLabel.setFont(font)
        self.CanvasLabel.setObjectName("CanvasLabel")
        self.CalibrateCanvasButton = QtWidgets.QPushButton(self.centralwidget)
        self.CalibrateCanvasButton.setGeometry(QtCore.QRect(70, 330, 81, 21))
        self.CalibrateCanvasButton.setObjectName("CalibrateCanvasButton")
        self.cmdLabel = QtWidgets.QLabel(self.centralwidget)
        self.cmdLabel.setGeometry(QtCore.QRect(20, 170, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmdLabel.setFont(font)
        self.cmdLabel.setAcceptDrops(False)
        self.cmdLabel.setAutoFillBackground(False)
        self.cmdLabel.setWordWrap(True)
        self.cmdLabel.setStyleSheet("")
        self.cmdLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cmdLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.cmdLabel.setObjectName("cmdLabel")
        self.InfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfoLabel.setGeometry(QtCore.QRect(10, 131, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setAutoFillBackground(False)
        self.InfoLabel.setStyleSheet("")
        self.InfoLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.InfoLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.InfoLabel.setObjectName("InfoLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 11, 171, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 361, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(356, 20, 31, 331))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-10, 20, 41, 331))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 340, 361, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(165, 20, 31, 111))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 290, 361, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.URLLabel = QtWidgets.QLabel(self.centralwidget)
        self.URLLabel.setGeometry(QtCore.QRect(180, 295, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.URLLabel.setFont(font)
        self.URLLabel.setObjectName("URLLabel")
        self.URLLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.URLLineEdit.setGeometry(QtCore.QRect(180, 320, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.URLLineEdit.setFont(font)
        self.URLLineEdit.setText("")
        self.URLLineEdit.setObjectName("URLLineEdit")
        self.AdaptiveCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AdaptiveCheckBox.setGeometry(QtCore.QRect(350, 80, 61, 21))
        self.AdaptiveCheckBox.setText("")
        self.AdaptiveCheckBox.setObjectName("AdaptiveCheckBox")
        self.AdaptiveLabel = QtWidgets.QLabel(self.centralwidget)
        self.AdaptiveLabel.setGeometry(QtCore.QRect(300, 75, 47, 31))
        self.AdaptiveLabel.setObjectName("AdaptiveLabel")
        self.LayersLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LayersLineEdit.setGeometry(QtCore.QRect(180, 80, 31, 20))
        self.LayersLineEdit.setObjectName("LayersLineEdit")
        self.BrushSizetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.BrushSizetLineEdit.setGeometry(QtCore.QRect(180, 50, 31, 20))
        self.BrushSizetLineEdit.setObjectName("BrushSizetLineEdit")
        self.LayersLabel = QtWidgets.QLabel(self.centralwidget)
        self.LayersLabel.setGeometry(QtCore.QRect(221, 80, 71, 21))
        self.LayersLabel.setObjectName("LayersLabel")
        self.BrushSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrushSizeLabel.setGeometry(QtCore.QRect(220, 50, 31, 21))
        self.BrushSizeLabel.setObjectName("BrushSizeLabel")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 90, 361, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 60, 361, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 31, 171, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(160, 300, 41, 51))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.PercentLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PercentLineEdit.setGeometry(QtCore.QRect(180, 110, 31, 20))
        self.PercentLineEdit.setObjectName("PercentLineEdit")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(10, 155, 361, 31))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.DrawButton = QtWidgets.QPushButton(self.centralwidget)
        self.DrawButton.setGeometry(QtCore.QRect(290, 270, 81, 31))
        self.DrawButton.setObjectName("DrawButton")
        self.QuitDrawLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuitDrawLabel.setGeometry(QtCore.QRect(290, 250, 81, 21))
        self.QuitDrawLabel.setObjectName("QuitDrawLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 379, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #  connecting the buttons to functions
        self.DrawButton.clicked.connect(self.pressedDraw)
        self.CalibrateCanvasButton.clicked.connect(self.pressedCalCanvas)
        self.CalibrateColorsButton.clicked.connect(self.pressedCalColors)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"nuspli v{version}"))
        self.DrawmodeLabel.setText(_translate("MainWindow", "Drawing Mode:"))
        self.DrawmodeBox.setItemText(0, _translate("MainWindow", "Canny - outlines human like"))
        self.DrawmodeBox.setItemText(1, _translate("MainWindow", "Canny - outlines just lines"))
        self.DrawmodeBox.setItemText(2, _translate("MainWindow", "Floyd-Steinberg-Dithering - colored"))
        self.DrawmodeBox.setItemText(3, _translate("MainWindow", "Floyd-Steinberg-Dithering - black and white"))
        self.DrawmodeBox.setItemText(4, _translate("MainWindow", "Quantized Image - color by color"))
        self.DrawmodeBox.setItemText(5, _translate("MainWindow", "Quantized Image - line by line"))
        self.BrushLabel.setText(_translate("MainWindow", "Brush Size:"))
        self.LayerLabel.setText(_translate("MainWindow", "Layers:"))
        self.SpeedLabel.setText(_translate("MainWindow", "Speed:"))
        self.PercentLabel.setText(_translate("MainWindow", "%"))
        self.CalibrateColorsButton.setText(_translate("MainWindow", "Calibrate"))
        self.ColorsLabel.setText(_translate("MainWindow", "Colors"))
        self.CanvasLabel.setText(_translate("MainWindow", "Canvas"))
        self.CalibrateCanvasButton.setText(_translate("MainWindow", "Calibrate"))
        self.cmdLabel.setText(_translate("MainWindow", ""))
        self.InfoLabel.setText(_translate("MainWindow", "nuspli - draw bot"))
        self.URLLabel.setText(_translate("MainWindow", "Image URL"))
        self.AdaptiveLabel.setText(_translate("MainWindow", "adaptive"))
        self.LayersLabel.setText(_translate("MainWindow", "1 - 10          or"))
        self.BrushSizeLabel.setText(_translate("MainWindow", "1 - 10"))
        self.DrawButton.setText(_translate("MainWindow", "Draw"))
        self.QuitDrawLabel.setText(_translate("MainWindow", "Press q to quit"))

    def pressedDraw(self):
        print("[DEBUG] draw button pressed")
        draw.draw(self)

    def pressedCalCanvas(self):
        print("[DEBUG] calibrate canvas button pressed")
        calibrate.calCanvas(self)

    def pressedCalColors(self):
        print("[DEBUG] calibrate colors button pressed")
        calibrate.calColors(self)

if __name__ == "__main__":
    print("[DEBUG] starting gui")
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    print("[DEBUG] gui started...")
    MainWindow.show()
    sys.exit(app.exec_())
